# Lab 1: Logistic Regression

## Lab Instruction 

In this lab, you are to create a logistic regression model to predict the sale price of <br>
houses (Low, High) from a given set of attributes. <br>
The data file is`lab1_dataset.csv` <br>
Note that you need to explore and process/drop attributes, <br>
and map numerical values of sale prices to categorical values (Low, High)

###  1. Import the Dataset and Learn About the Data


In [71]:
import pandas as pd
import numpy as np

In [1]:

pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

df

NameError: name 'pd' is not defined

In [72]:
df = pd.read_csv("lab1_dataset.csv",sep=",")

In [7]:
df.describe()

Id     1stFlrSF   Fireplaces     FullBath  OpenPorchSF  \
count  1460.000000  1460.000000  1460.000000  1460.000000  1460.000000   
mean    730.500000  1162.626712     0.613014     1.565068    46.660274   
std     421.610009   386.587738     0.644666     0.550916    66.256028   
min       1.000000   334.000000     0.000000     0.000000     0.000000   
25%     365.750000   882.000000     0.000000     1.000000     0.000000   
50%     730.500000  1087.000000     1.000000     2.000000    25.000000   
75%    1095.250000  1391.250000     1.000000     2.000000    68.000000   
max    1460.000000  4692.000000     3.000000     3.000000   547.000000   

       GarageYrBlt  OverallQual    YearBuilt   GarageArea  TotRmsAbvGrd  \
count  1379.000000  1460.000000  1460.000000  1460.000000   1460.000000   
mean   1978.506164     6.099315  1971.267808   472.980137      6.517808   
std      24.689725     1.382997    30.202904   213.804841      1.625393   
min    1900.000000     1.000000  1872.000000     0.000000      2.000000   
25%    1961.000000     5.000000  1954.000000   334.500000      5.000000   
50%    1980.000000     6.000000  1973.000000   480.000000      6.000000   
75%    2002.000000     7.000000  2000.000000   576.000000      7.000000   
max    2010.000000    10.000000  2010.000000  1418.000000     14.000000   

        GarageCars    GrLivArea  YearRemodAdd  LotFrontage      SalePrice  
count  1460.000000  1460.000000   1460.000000  1201.000000    1460.000000  
mean      1.767123  1515.463699   1984.865753    70.049958  180921.195890  
std       0.747315   525.480383     20.645407    24.284752   79442.502883  
min       0.000000   334.000000   1950.000000    21.000000   34900.000000  
25%       1.000000  1129.500000   1967.000000    59.000000  129975.000000  
50%       2.000000  1464.000000   1994.000000    69.000000  163000.000000  
75%       2.000000  1776.750000   2004.000000    80.000000  214000.000000  
max       4.000000  5642.000000   2010.000000   313.000000  755000.000000

In [8]:
df.head()


Id Foundation  1stFlrSF KitchenQual  Fireplaces HeatingQC  FullBath  \
0   1      PConc       856          Gd           0        Ex         2   
1   2     CBlock      1262          TA           1        Ex         2   
2   3      PConc       920          Gd           1        Ex         2   
3   4     BrkTil       961          Gd           1        Gd         1   
4   5      PConc      1145          Gd           1        Ex         2   

  BsmtQual  OpenPorchSF  GarageYrBlt    ...     BsmtFinType1  YearBuilt  \
0       Gd           61       2003.0    ...              GLQ       2003   
1       Gd            0       1976.0    ...              ALQ       1976   
2       Gd           42       2001.0    ...              GLQ       2001   
3       TA           35       1998.0    ...              ALQ       1915   
4       Gd           84       2000.0    ...              GLQ       2000   

  GarageArea  TotRmsAbvGrd  GarageCars  GrLivArea  YearRemodAdd  LotFrontage  \
0        548             8           2       1710          2003         65.0   
1        460             6           2       1262          1976         80.0   
2        608             6           2       1786          2002         68.0   
3        642             7           3       1717          1970         60.0   
4        836             9           3       2198          2000         84.0   

   Fence  SalePrice  
0    NaN     208500  
1    NaN     181500  
2    NaN     223500  
3    NaN     140000  
4    NaN     250000  

[5 rows x 22 columns]

In [9]:
df.dtypes


Id                int64
Foundation       object
1stFlrSF          int64
KitchenQual      object
Fireplaces        int64
HeatingQC        object
FullBath          int64
BsmtQual         object
OpenPorchSF       int64
GarageYrBlt     float64
ExterQual        object
OverallQual       int64
BsmtFinType1     object
YearBuilt         int64
GarageArea        int64
TotRmsAbvGrd      int64
GarageCars        int64
GrLivArea         int64
YearRemodAdd      int64
LotFrontage     float64
Fence            object
SalePrice         int64
dtype: object

In [10]:
df[1:5]

Id Foundation  1stFlrSF KitchenQual  Fireplaces HeatingQC  FullBath  \
1   2     CBlock      1262          TA           1        Ex         2   
2   3      PConc       920          Gd           1        Ex         2   
3   4     BrkTil       961          Gd           1        Gd         1   
4   5      PConc      1145          Gd           1        Ex         2   

  BsmtQual  OpenPorchSF  GarageYrBlt    ...     BsmtFinType1  YearBuilt  \
1       Gd            0       1976.0    ...              ALQ       1976   
2       Gd           42       2001.0    ...              GLQ       2001   
3       TA           35       1998.0    ...              ALQ       1915   
4       Gd           84       2000.0    ...              GLQ       2000   

  GarageArea  TotRmsAbvGrd  GarageCars  GrLivArea  YearRemodAdd  LotFrontage  \
1        460             6           2       1262          1976         80.0   
2        608             6           2       1786          2002         68.0   
3        642             7           3       1717          1970         60.0   
4        836             9           3       2198          2000         84.0   

   Fence  SalePrice  
1    NaN     181500  
2    NaN     223500  
3    NaN     140000  
4    NaN     250000  

[4 rows x 22 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 22 columns):
Id              1460 non-null int64
Foundation      1460 non-null object
1stFlrSF        1460 non-null int64
KitchenQual     1460 non-null object
Fireplaces      1460 non-null int64
HeatingQC       1460 non-null object
FullBath        1460 non-null int64
BsmtQual        1423 non-null object
OpenPorchSF     1460 non-null int64
GarageYrBlt     1379 non-null float64
ExterQual       1460 non-null object
OverallQual     1460 non-null int64
BsmtFinType1    1423 non-null object
YearBuilt       1460 non-null int64
GarageArea      1460 non-null int64
TotRmsAbvGrd    1460 non-null int64
GarageCars      1460 non-null int64
GrLivArea       1460 non-null int64
YearRemodAdd    1460 non-null int64
LotFrontage     1201 non-null float64
Fence           281 non-null object
SalePrice       1460 non-null int64
dtypes: float64(2), int64(13), object(7)
memory usage: 251.0+ KB


In [12]:
df.shape

(1460, 22)

In [13]:
df.describe()

Id     1stFlrSF   Fireplaces     FullBath  OpenPorchSF  \
count  1460.000000  1460.000000  1460.000000  1460.000000  1460.000000   
mean    730.500000  1162.626712     0.613014     1.565068    46.660274   
std     421.610009   386.587738     0.644666     0.550916    66.256028   
min       1.000000   334.000000     0.000000     0.000000     0.000000   
25%     365.750000   882.000000     0.000000     1.000000     0.000000   
50%     730.500000  1087.000000     1.000000     2.000000    25.000000   
75%    1095.250000  1391.250000     1.000000     2.000000    68.000000   
max    1460.000000  4692.000000     3.000000     3.000000   547.000000   

       GarageYrBlt  OverallQual    YearBuilt   GarageArea  TotRmsAbvGrd  \
count  1379.000000  1460.000000  1460.000000  1460.000000   1460.000000   
mean   1978.506164     6.099315  1971.267808   472.980137      6.517808   
std      24.689725     1.382997    30.202904   213.804841      1.625393   
min    1900.000000     1.000000  1872.000000     0.000000      2.000000   
25%    1961.000000     5.000000  1954.000000   334.500000      5.000000   
50%    1980.000000     6.000000  1973.000000   480.000000      6.000000   
75%    2002.000000     7.000000  2000.000000   576.000000      7.000000   
max    2010.000000    10.000000  2010.000000  1418.000000     14.000000   

        GarageCars    GrLivArea  YearRemodAdd  LotFrontage      SalePrice  
count  1460.000000  1460.000000   1460.000000  1201.000000    1460.000000  
mean      1.767123  1515.463699   1984.865753    70.049958  180921.195890  
std       0.747315   525.480383     20.645407    24.284752   79442.502883  
min       0.000000   334.000000   1950.000000    21.000000   34900.000000  
25%       1.000000  1129.500000   1967.000000    59.000000  129975.000000  
50%       2.000000  1464.000000   1994.000000    69.000000  163000.000000  
75%       2.000000  1776.750000   2004.000000    80.000000  214000.000000  
max       4.000000  5642.000000   2010.000000   313.000000  755000.000000

In [14]:
df.select_dtypes(include=['int64','float64']).describe()

Id     1stFlrSF   Fireplaces     FullBath  OpenPorchSF  \
count  1460.000000  1460.000000  1460.000000  1460.000000  1460.000000   
mean    730.500000  1162.626712     0.613014     1.565068    46.660274   
std     421.610009   386.587738     0.644666     0.550916    66.256028   
min       1.000000   334.000000     0.000000     0.000000     0.000000   
25%     365.750000   882.000000     0.000000     1.000000     0.000000   
50%     730.500000  1087.000000     1.000000     2.000000    25.000000   
75%    1095.250000  1391.250000     1.000000     2.000000    68.000000   
max    1460.000000  4692.000000     3.000000     3.000000   547.000000   

       GarageYrBlt  OverallQual    YearBuilt   GarageArea  TotRmsAbvGrd  \
count  1379.000000  1460.000000  1460.000000  1460.000000   1460.000000   
mean   1978.506164     6.099315  1971.267808   472.980137      6.517808   
std      24.689725     1.382997    30.202904   213.804841      1.625393   
min    1900.000000     1.000000  1872.000000     0.000000      2.000000   
25%    1961.000000     5.000000  1954.000000   334.500000      5.000000   
50%    1980.000000     6.000000  1973.000000   480.000000      6.000000   
75%    2002.000000     7.000000  2000.000000   576.000000      7.000000   
max    2010.000000    10.000000  2010.000000  1418.000000     14.000000   

        GarageCars    GrLivArea  YearRemodAdd  LotFrontage      SalePrice  
count  1460.000000  1460.000000   1460.000000  1201.000000    1460.000000  
mean      1.767123  1515.463699   1984.865753    70.049958  180921.195890  
std       0.747315   525.480383     20.645407    24.284752   79442.502883  
min       0.000000   334.000000   1950.000000    21.000000   34900.000000  
25%       1.000000  1129.500000   1967.000000    59.000000  129975.000000  
50%       2.000000  1464.000000   1994.000000    69.000000  163000.000000  
75%       2.000000  1776.750000   2004.000000    80.000000  214000.000000  
max       4.000000  5642.000000   2010.000000   313.000000  755000.000000

###  2. Preprocessing

Use techniques that you have learned to preprocess the data. For example, 
-  Remove non-informative features
-  Remove features with too many NA
-  Remove rows with incomplete data
-  Remove features with highly unbalanced labels
-  Encode categorical variables as appropriate

In [15]:
df_copy = df.copy()

In [16]:
df_copy.isnull().sum() #check null

Id                 0
Foundation         0
1stFlrSF           0
KitchenQual        0
Fireplaces         0
HeatingQC          0
FullBath           0
BsmtQual          37
OpenPorchSF        0
GarageYrBlt       81
ExterQual          0
OverallQual        0
BsmtFinType1      37
YearBuilt          0
GarageArea         0
TotRmsAbvGrd       0
GarageCars         0
GrLivArea          0
YearRemodAdd       0
LotFrontage      259
Fence           1179
SalePrice          0
dtype: int64

In [17]:
df_copy['GarageYrBlt'].isnull().sum()


81

In [18]:
del df_copy['Fence'] 

In [19]:
df_copy.isnull().sum()

Id                0
Foundation        0
1stFlrSF          0
KitchenQual       0
Fireplaces        0
HeatingQC         0
FullBath          0
BsmtQual         37
OpenPorchSF       0
GarageYrBlt      81
ExterQual         0
OverallQual       0
BsmtFinType1     37
YearBuilt         0
GarageArea        0
TotRmsAbvGrd      0
GarageCars        0
GrLivArea         0
YearRemodAdd      0
LotFrontage     259
SalePrice         0
dtype: int64

In [20]:
df_copy['LotFrontage']

0        65.0
1        80.0
2        68.0
3        60.0
4        84.0
5        85.0
6        75.0
7         NaN
8        51.0
9        50.0
10       70.0
11       85.0
12        NaN
13       91.0
14        NaN
15       51.0
16        NaN
17       72.0
18       66.0
19       70.0
20      101.0
21       57.0
22       75.0
23       44.0
24        NaN
25      110.0
26       60.0
27       98.0
28       47.0
29       60.0
        ...  
1430     60.0
1431      NaN
1432     60.0
1433     93.0
1434     80.0
1435     80.0
1436     60.0
1437     96.0
1438     90.0
1439     80.0
1440     79.0
1441      NaN
1442     85.0
1443      NaN
1444     63.0
1445     70.0
1446      NaN
1447     80.0
1448     70.0
1449     21.0
1450     60.0
1451     78.0
1452     35.0
1453     90.0
1454     62.0
1455     62.0
1456     85.0
1457     66.0
1458     68.0
1459     75.0
Name: LotFrontage, Length: 1460, dtype: float64

In [21]:
df_copy.isnull().shape

(1460, 21)

In [22]:
df_copy.select_dtypes(include=['object']).describe()

Foundation KitchenQual HeatingQC BsmtQual ExterQual BsmtFinType1
count        1460        1460      1460     1423      1460         1423
unique          6           4         5        4         4            6
top         PConc          TA        Ex       TA        TA          Unf
freq          647         735       741      649       906          430

In [23]:
df_copy = df_copy.dropna(subset=['BsmtQual','BsmtFinType1','GarageYrBlt','LotFrontage'])

In [24]:
df_copy.SalePrice.hist()

In [25]:
df_copy['SalePrice_HL'] = pd.qcut(df_copy.SalePrice,q=[0,0.5,1],labels=['Low','High'])

In [26]:
df_copy.info


<bound method DataFrame.info of         Id Foundation  1stFlrSF KitchenQual  Fireplaces HeatingQC  FullBath  \
0        1      PConc       856          Gd           0        Ex         2   
1        2     CBlock      1262          TA           1        Ex         2   
2        3      PConc       920          Gd           1        Ex         2   
3        4     BrkTil       961          Gd           1        Gd         1   
4        5      PConc      1145          Gd           1        Ex         2   
5        6       Wood       796          TA           0        Ex         1   
6        7      PConc      1694          Gd           1        Ex         2   
8        9     BrkTil      1022          TA           2        Gd         2   
9       10     BrkTil      1077          TA           2        Ex         1   
10      11     CBlock      1040          TA           0        Ex         1   
11      12      PConc      1182          Ex           2        Ex         3   
13      14      PCon

In [27]:
Sale = {'High':1,'Low':0}
df_copy['SalePrice_HL'] = df_copy['SalePrice_HL'].replace(Sale)

In [28]:
df_copy.select_dtypes(include=['object']).describe()

Foundation KitchenQual HeatingQC BsmtQual ExterQual BsmtFinType1
count        1103        1103      1103     1103      1103         1103
unique          5           4         5        4         4            6
top         PConc          TA        Ex       TA        TA          Unf
freq          527         528       602      486       647          347

In [29]:
df_copy2 = df_copy.copy()

In [30]:
quality  = {'Po':0 ,'Fa':1,'TA':2,'Gd':3,'Ex':4}
df_copy2['KitchenQual'] = df_copy2['KitchenQual'].replace(quality)
df_copy2['HeatingQC'] = df_copy2['HeatingQC'].replace(quality)
df_copy2['BsmtQual'] = df_copy2['BsmtQual'].replace(quality)
df_copy2['ExterQual'] = df_copy2['ExterQual'].replace(quality)

In [31]:
quality2  = {'NA':0 ,'Unf':1,'LwQ':2,'Rec':3,'BLQ':4,'ALQ':5,'GLQ':6}
df_copy2['BsmtFinType1'] = df_copy2['BsmtFinType1'].replace(quality2)


In [32]:
df_copy3 = pd.get_dummies(df_copy2,columns = ['Foundation'])

### 3. Model Training 
We will use Scikit-learn package to build a model.
- http://scikit-learn.org/stable/

Model Evaluation Method
- Split into train set and test set

In [33]:
traindata_x = df_copy3.drop(['SalePrice','SalePrice_HL','Id'],axis = 1)
traindata_y = df_copy3.SalePrice_HL

In [34]:
traindata_x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1103 entries, 0 to 1459
Data columns (total 23 columns):
1stFlrSF             1103 non-null int64
KitchenQual          1103 non-null int64
Fireplaces           1103 non-null int64
HeatingQC            1103 non-null int64
FullBath             1103 non-null int64
BsmtQual             1103 non-null int64
OpenPorchSF          1103 non-null int64
GarageYrBlt          1103 non-null float64
ExterQual            1103 non-null int64
OverallQual          1103 non-null int64
BsmtFinType1         1103 non-null int64
YearBuilt            1103 non-null int64
GarageArea           1103 non-null int64
TotRmsAbvGrd         1103 non-null int64
GarageCars           1103 non-null int64
GrLivArea            1103 non-null int64
YearRemodAdd         1103 non-null int64
LotFrontage          1103 non-null float64
Foundation_BrkTil    1103 non-null uint8
Foundation_CBlock    1103 non-null uint8
Foundation_PConc     1103 non-null uint8
Foundation_Stone     1103 no

In [35]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(traindata_x,traindata_y,test_size = 0.4,random_state = 0)

In [36]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(661, 23) (661,)
(442, 23) (442,)


In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

- Fit Logistic Regression model

In [38]:
from sklearn import linear_model
lr = linear_model.LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

### 4. Model Tuning &  Result Analysis 

Analyze the model results. Do you think the model is good enough? <br>
Does it overfit or underfit the data? <br>
Explain and provide evidence to support your claims.

Does it overfit or underfit the data?  Explain and provide evidence to support your claims
Ans underfit because accuracy of train data and test data not different



In [39]:
yhat_train = lr.predict(x_train)
from sklearn.metrics import accuracy_score
acc_train = accuracy_score(y_train,yhat_train)
print("Accuracy from train dataset :"+str(acc_train*100))

Accuracy from train dataset :93.04084720121028


In [40]:
yhat_test = lr.predict(x_test)

acc_test = accuracy_score(y_test,yhat_test)
print("Accuracy from test dataset :"+str(acc_test*100))

Accuracy from test dataset :91.6289592760181


In [41]:
from sklearn.metrics import confusion_matrix
print("confusion matrix from train data set\n")
print(confusion_matrix(y_train,yhat_train))

confusion matrix from train data set

[[292  26]
 [ 20 323]]


In [42]:
from sklearn.metrics import confusion_matrix
print("confusion matrix from test data set\n")
print(confusion_matrix(y_test,yhat_test))

confusion matrix from test data set

[[215  20]
 [ 17 190]]


In [48]:
from sklearn.metrics import f1_score,accuracy_score,precision_score,recall_score

print("==== Accuracy/Precision/Recall/F1 from train data set ==== \n")
f1 = f1_score(y_train,yhat_train)
acc = accuracy_score(y_train,yhat_train)
precision = precision_score(y_train,yhat_train)
recall = recall_score(y_train,yhat_train)
print("Accuracy = "+str(acc*100))
print("Precision = "+str(precision*100))
print("Recall = "+str(recall*100))
print("F1 = "+str(f1*100))


==== Accuracy/Precision/Recall/F1 from train data set ==== 

Accuracy = 93.04084720121028
Precision = 92.55014326647564
Recall = 94.16909620991254
F1 = 93.35260115606937


In [49]:
print("==== Accuracy/Precision/Recall/F1 from train data set ====\n")
f12 = f1_score(y_test,yhat_test)
acc2 = accuracy_score(y_test,yhat_test)
precision2 = precision_score(y_test,yhat_test)
recall2 = recall_score(y_test,yhat_test)
print("Accuracy = "+str(acc2*100))
print("Precision = "+str(precision2*100))
print("Recall = "+str(recall2*100))
print("F1 = "+str(f12*100))

==== Accuracy/Precision/Recall/F1 from train data set ====

Accuracy = 91.6289592760181
Precision = 90.47619047619048
Recall = 91.78743961352657
F1 = 91.12709832134293


In [51]:
from sklearn.metrics import classification_report
print("==== classification report from train data set ====\n")
print(classification_report(y_train,yhat_train,target_names = ['no','yes']))

==== classification report from train data set ====

             precision    recall  f1-score   support

         no       0.94      0.92      0.93       318
        yes       0.93      0.94      0.93       343

avg / total       0.93      0.93      0.93       661



In [52]:
print("==== classification report from test data set ====\n")
print(classification_report(y_test,yhat_test,target_names = ['no','yes']))

==== classification report from test data set ====

             precision    recall  f1-score   support

         no       0.93      0.91      0.92       235
        yes       0.90      0.92      0.91       207

avg / total       0.92      0.92      0.92       442



### 5. (Optional) Mutlinomial Logistic Regression Model

Binning the sale price into three classes : `Low`, `Medium`, `High`.
Then, apply the logistic regression model and evaluate the model performance. <br>
See http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [56]:
df_copy = df.copy()

In [57]:
del df_copy['Fence'] 

In [58]:
df_copy = df_copy.dropna(subset=['BsmtQual','BsmtFinType1','GarageYrBlt','LotFrontage'])

In [59]:
df_copy['SalePrice_HL'] = pd.qcut(df_copy.SalePrice,3,labels=['Low','Medium','High'])
df_copy['SalePrice_HL']

0         High
1       Medium
2         High
3          Low
4         High
5       Medium
6         High
8          Low
9          Low
10         Low
11        High
13        High
15         Low
18      Medium
19         Low
20        High
21         Low
22        High
23         Low
25        High
26         Low
27        High
28        High
29         Low
30         Low
32      Medium
33      Medium
34        High
35        High
36      Medium
         ...  
1420    Medium
1421       Low
1422       Low
1425    Medium
1426      High
1427       Low
1428       Low
1430    Medium
1432       Low
1433    Medium
1434    Medium
1435    Medium
1436       Low
1437      High
1438    Medium
1439      High
1440    Medium
1442      High
1444    Medium
1445       Low
1447      High
1448       Low
1451      High
1452    Medium
1454    Medium
1455    Medium
1456      High
1457      High
1458    Medium
1459    Medium
Name: SalePrice_HL, Length: 1103, dtype: category
Categories (3, object): [Low < Medi

In [60]:
Sale = {'High':3,'Medium':2,'Low':1}
df_copy['SalePrice_HL'] = df_copy['SalePrice_HL'].replace(Sale)

In [61]:
df_copy2 = df_copy.copy()
quality  = {'Po':0 ,'Fa':1,'TA':2,'Gd':3,'Ex':4}
df_copy2['KitchenQual'] = df_copy2['KitchenQual'].replace(quality)
df_copy2['HeatingQC'] = df_copy2['HeatingQC'].replace(quality)
df_copy2['BsmtQual'] = df_copy2['BsmtQual'].replace(quality)
df_copy2['ExterQual'] = df_copy2['ExterQual'].replace(quality)

In [62]:
quality2  = {'NA':0 ,'Unf':1,'LwQ':2,'Rec':3,'BLQ':4,'ALQ':5,'GLQ':6}
df_copy2['BsmtFinType1'] = df_copy2['BsmtFinType1'].replace(quality2)


In [63]:
df_copy3 = pd.get_dummies(df_copy2,columns = ['Foundation'])

In [2]:
traindata_x = df_copy3.drop(['SalePrice','SalePrice_HL','Id'],axis = 1)
traindata_y = df_copy3.SalePrice_HL

NameError: name 'df_copy3' is not defined

In [1]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(traindata_x,traindata_y,test_size = 0.3,random_state = 0)

NameError: name 'traindata_x' is not defined

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
from sklearn import linear_model
lr = linear_model.LogisticRegression( warm_start = True,solver='lbfgs', max_iter=60000, multi_class='multinomial' )
lr.fit(x_train,y_train)

In [81]:
yhat_train = lr.predict(x_train)
from sklearn.metrics import accuracy_score
acc_train = accuracy_score(y_train,yhat_train)
print("Accuracy from train dataset :"+str(acc_train*100))

Accuracy from train dataset :83.66111951588502


In [82]:
yhat_test = lr.predict(x_test)

acc_test = accuracy_score(y_test,yhat_test)
print("Accuracy from test dataset :"+str(acc_test*100))

Accuracy from test dataset :82.12669683257919


In [83]:
from sklearn.metrics import confusion_matrix
print("confusion matrix from train data set\n")
print(confusion_matrix(y_train,yhat_train))

confusion matrix from train data set

[[183  28   1]
 [ 30 168  23]
 [  1  25 202]]


In [84]:
from sklearn.metrics import confusion_matrix
print("confusion matrix from test data set\n")
print(confusion_matrix(y_test,yhat_test))

confusion matrix from test data set

[[130  27   0]
 [ 24 110  11]
 [  1  16 123]]


In [87]:
from sklearn.metrics import classification_report
print("==== classification report from train data set ====\n")
print(classification_report(y_train,yhat_train,target_names = ['no','yes']))

==== classification report from train data set ====

             precision    recall  f1-score   support

         no       0.86      0.86      0.86       212
        yes       0.76      0.76      0.76       221

avg / total       0.84      0.84      0.84       661



C:\Users\FongInWza2007eiei\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1428: UserWarning: labels size, 3, does not match size of target_names, 2
  .format(len(labels), len(target_names))


In [88]:
print("==== classification report from test data set ====\n")
print(classification_report(y_test,yhat_test,target_names = ['no','yes']))

==== classification report from test data set ====

             precision    recall  f1-score   support

         no       0.84      0.83      0.83       157
        yes       0.72      0.76      0.74       145

avg / total       0.82      0.82      0.82       442



C:\Users\FongInWza2007eiei\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1428: UserWarning: labels size, 3, does not match size of target_names, 2
  .format(len(labels), len(target_names))
